### ISSUE TITLE
Sprint 1 Completed

### ISSUE THREAD

**Issue by MystKnight** [walk-a-lot/explore#38]
/cc @codepathreview @codepath

https://s3.amazonaws.com/uploads.hipchat.com/14477/52355/c1I5NjMmrllTsnB/explore2.gif

**Comment by codepathreview** [comment]
:+1:  Nice work creating wire-frames and creating stories for sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:

* Well created detailed stories/tasks.
* Nice way of splitting a parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.
* Good job by everyone to (contribute) [https://github.com/walk-a-lot/explore/graphs/contributors] to the project.  
* Impressed that you are already thinking about documenting overall strategy and most design decisions.
* Good to see that your team created regular commits to sync up your code to avoid having multiple conflicts at the end.
* Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on. It is those little extra things you do that make everything feel more polished and desirable to use.
